export const MOCK_STORES = [
    {
      id: "1",
      name: "Knead Bakery",
      category: "Bakery",
      description: "Artisan sourdough, pastries and fresh-baked goods made daily in our Cape Town kitchen. Every bag is a delicious surprise of the day's best.",
      image_url: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80",
      banner_url: "https://images.unsplash.com/photo-1549931319-a545dcf3bc7c?w=800&q=80",
      rating: 4.8,
      distance_km: 0.6,
      address: "Shop 4, Kloof Street, Gardens",
      city: "Cape Town",
      bag_price: 45,
      bags_available: 5,
      pickup_start: "5:30pm",
      pickup_end: "7:00pm",
      bag_description: "A surprise selection of today's unsold fresh items — think sourdough loaves, croissants, muffins, and more.",
      food_saved_kg: 1.2,
      is_active: true,
    },
    {
      id: "2",
      name: "The Wok",
      category: "Restaurant",
      description: "Pan-Asian street food with a Cape Town twist. Our Still Fresh bags pack the best of today's kitchen.",
      image_url: "https://images.unsplash.com/photo-1559847844-5315695dadae?w=600&q=80",
      banner_url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80",
      rating: 4.5,
      distance_km: 1.2,
      address: "22 Long Street, Cape Town CBD",
      city: "Cape Town",
      bag_price: 50,
      bags_available: 3,
      pickup_start: "8:30pm",
      pickup_end: "9:30pm",
      bag_description: "Rescue tonight's unsold prepared dishes — rice bowls, dumplings, noodles and more.",
      food_saved_kg: 1.8,
      is_active: true,
    },
    {
      id: "3",
      name: "Woolworths Food",
      category: "Supermarket",
      description: "Quality food that deserves a home. Our daily surplus bags are packed with fresh produce, deli items and prepared meals.",
      image_url: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&q=80",
      banner_url: "https://images.unsplash.com/photo-1604719312566-8912e9c8a213?w=800&q=80",
      rating: 4.6,
      distance_km: 0.9,
      address: "V&A Waterfront, Cape Town",
      city: "Cape Town",
      bag_price: 35,
      bags_available: 8,
      pickup_start: "6:00pm",
      pickup_end: "8:00pm",
      bag_description: "Premium surplus from fresh produce, bakery, and ready meals. Value guaranteed.",
      food_saved_kg: 2.1,
      is_active: true,
    },
    {
      id: "4",
      name: "Rosetta Coffee",
      category: "Cafe",
      description: "Specialty coffee roasters with world-class pastries. Our rescue bags are perfect for coffee lovers.",
      image_url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80",
      banner_url: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800&q=80",
      rating: 4.9,
      distance_km: 0.4,
      address: "8 Wale Street, Bo-Kaap",
      city: "Cape Town",
      bag_price: 25,
      bags_available: 2,
      pickup_start: "4:00pm",
      pickup_end: "5:00pm",
      bag_description: "End-of-day pastries, sandwiches and sweet treats from our specialty kitchen.",
      food_saved_kg: 0.8,
      is_active: true,
    },
    {
      id: "5",
      name: "Giovanni's Deli World",
      category: "Deli",
      description: "Cape Town's finest Italian deli since 1984. Daily surplus includes imported cheeses, cured meats, and fresh pasta.",
      image_url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80",
      banner_url: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80",
      rating: 4.7,
      distance_km: 1.8,
      address: "103 Main Road, Green Point",
      city: "Cape Town",
      bag_price: 55,
      bags_available: 4,
      pickup_start: "6:30pm",
      pickup_end: "7:30pm",
      bag_description: "Premium deli surplus — cheeses, charcuterie, fresh pasta, and more Italian goodness.",
      food_saved_kg: 1.5,
      is_active: true,
    },
    {
      id: "6",
      name: "Tribe Coffee",
      category: "Cafe",
      description: "Award-winning specialty coffee and bakes. Rescue our lovingly crafted goods before they go to waste.",
      image_url: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600&q=80",
      banner_url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80",
      rating: 4.8,
      distance_km: 2.1,
      address: "45 Church Street, Cape Town",
      city: "Cape Town",
      bag_price: 30,
      bags_available: 6,
      pickup_start: "3:30pm",
      pickup_end: "4:30pm",
      bag_description: "Beautiful sourdough, pastries, cakes and other baked goods made with love.",
      food_saved_kg: 1.0,
      is_active: true,
    },
  ];
  
  export const CATEGORIES = ["All", "Bakery", "Restaurant", "Supermarket", "Cafe", "Deli"];